---
title: "Research"
---

***

My research focuses on **evaluating** and **applying** advanced statistical methods to behavioral data. My research falls into two broad categories: statistical research and applied research.

[CV](files/SCoxe_CV 053122.pdf) / [`r fontawesome::fa(name = "google", fill = "steelblue")` scholar](https://scholar.google.com/citations?user=fZEA0AkAAAAJ)

## Statistical research

### **Generalized linear model (GLiM)** 

GLiMs are a broad family of statistical models that extend linear regression analysis to a wider range of outcome variable distributions and error structures. I use *simulations* to explore the performance of these models. I am particularly interested in the statistical characteristics of counts outcome variables, especially in statistical mediation models.

- **Coxe, S.** (2019, March). Counts and Frequencies in Psychological Research. At Blending Psychology and Methods: A Conference in Honor of Professor Leona Aiken. Tempe, AZ. March 22, 2019.
- Aiken, L. S., Mistler, S. A., **Coxe, S.**, and West, S. G. (2015). Analyzing Count Variables in Individuals and Groups: Single and Multilevel Models. *Group Processes and Intergroup Relations, 18*, 290-314. doi: 10.1177/1368430214556702 
- **Coxe, S.**, Aiken, L. S., and West, S. G. (2013). Generalized linear models. In T. Little (Ed.), *Oxford Handbook of Quantitative Methods, Volume 2*. New York: Oxford University Press. 
- **Coxe, S.** (2010). Mediation analysis of Poisson distributed count outcomes: Standard estimates of the mediated effect are not equivalent. Presented at the 8th Annual Society of Multivariate Experimental Psychology Graduate Student Pre-conference. Atlanta, GA. September 30, 2010.
- **Coxe, S.**, West, S. G., and Aiken, L. S. (2009). The analysis of count data: A gentle introduction to Poisson regression and its alternatives. Journal of *Personality Assessment, 91*, 121-136. 
  - Data from this paper: [SAS](files/jpapoisson.sas7bdat) / [SPSS](files/jpapoisson.sav) / [Text](files/jpapoisson.txt)

### **Integrative data analysis (IDA)** 

I am joint co-PI on [TIDAL](https://doi.org/10.1186/s12888-020-02734-6), an integrative data analysis project funded by [NIMH](https://reporter.nih.gov/project-details/9509965) combining data from 4 separate psychosocial interventions for teens who have been diagnosed with ADHD. The combined dataset is publicly available [here](https://nda.nih.gov/data_structure.html?short_name=tidal01). Among the methodological challenges in this project were harmonization of measures of ADHD symptoms (DSM-IV versus DSM-5) and parent depression symptoms (various measures) using moderated nonlinear factor analysis.

- [**Coxe, S.** (2023, April). Integrative data analysis: Latent profile analysis of adolescents with ADHD. At FIU Statistics Department Colloquium Series. Miami, FL. April 19, 2023.](files/StatColl2023.html)  
- **Coxe, S.** & Sibley, M. H. (2023). Harmonizing DSM-IV and DSM-5 versions of ADHD "A Criteria": An Item Response Theory Analysis. *Assessment, 30*, 606-617.[https://doi.org/10.1177/10731911211061299](https://doi.org/10.1177/10731911211061299)
- Zhao, X., **Coxe, S.**, Sibley, M. J., Zulauf-McCurdy, C.A., & Pettit, J. (2022). Harmonizing Depression Measures Across Studies: A Tutorial for Data Harmonization. *Prevention Science*. [https://doi.org/10.1007](https://doi.org/10.1007)  
- [**Coxe, S.** (2022, April). Integrative data analysis to further replicable science in psychology. At FIU Statistics Annual Mini-Conference in Statistical Methods and Mentoring. Miami, FL. April 8, 2022.](files/Coxe_Stats_040822.html)  
- Sibley, M. H., **Coxe, S.**, Stein, M.A., Meinzer, M. C., Valente, M. (2022). Predictors of Treatment Engagement and Response among Adolescents with ADHD: An Integrative Data Analysis. *Journal of the American Academy of Child and Adolescent and Psychiatry*.
- **Coxe, S.**, Sibley, M.H., & Becker, S.P. (2021). Presenting Problem Profiles for Adolescents with ADHD: Differences by Sex, Age, Race, and Family Adversity. *Child and Adolescent Mental Health, 26*, 228-237. 
- Sibley, M.H. & **Coxe, S.** (2020). The ADHD Teen Integrative Data Analysis Longitudinal (TIDAL) Dataset: Background, Methodology, and Aims. *BMC Psychiatry, 20*, 1-12. 

### **Statistical graphics and R shiny** 

I am interested in graphics as an aid to interpreting and communicating statistical models. To this end, I have developed `r fontawesome::fa(name = "r-project", fill = "steelblue")` **shiny** applications to calculate effect size for count regression models and to estimate confidence intervals for mediation models. `r fontawesome::fa(name = "r-project", fill = "steelblue")` **shiny** applications are **interactive, web-based** tools for statistical analysis and graphics.

- [RcountD](https://stefany.shinyapps.io/RcountD/): Estimate effect sizes for regression models for count models (Poisson regression and negative binomial regression). Standard multiplicative effect size (rate ratio) and standardized mean difference (Cohen's *d*) effect sizes are provided. Monte Carlo confidence intervals for each effect size are also given. 
  - [**Coxe, S.** (2018, February). Effect size measures for nonlinear count regression models. Poster presented at the American Statistical Association Conference on Statistical Practice. Portland, OR. February 15 – 17, 2018.](files/Coxe ASA CSP 020618.pdf)

- [SimpleMediation](https://stefany.shinyapps.io/SimpleMediation/): Estimate indirect (mediated) effect with Monte Carlo simulated confidence intervals. This app was developed for pedagogical purposes.

- I teach a course on **Statistical Graphics and Communication** in the Psychology department. This course covers a variety of topics, including **R**, **ggplot2**, **markdown**, and **shiny**. Most of the materials for the *first version* of the course from 2019 are available here: [https://stefanycoxe.github.io/graphics_2019/](https://stefanycoxe.github.io/graphics_2019/)

## Applied research 

My applied research takes place largely in the context of clinical and psychosocial interventions in the Psychology department and the Center for Children and Families. I also work with faculty in the departments of Epidemiology, Social Work, and Biomedical Engineering. These studies often include complex longitudinal designs, non-normally distributed outcome variables, and extensive missing data. 

- Zhao, X., **Coxe, S.**, Timmons, A., & Frazier, S. L. (2022). Mental Health Information-Seeking Online: A Google Trends Analysis of ADHD. *Administration and Policy in Mental Health and Mental Health Services Research, 49*, 357 - 373. [https://doi.org/10.1007/s10488-021-01168-w](https://doi.org/10.1007/s10488-021-01168-w)  
- Sibley, M.H., **Coxe, S.J.**, Page, T.P., Pelham, W.E., Yeguez, C.E., LaCount, P.A., & Barney, S. (2020). Four-Year Follow-up of High versus Low Intensity Summer Treatment for Adolescents with ADHD. *Journal of Clinical Child and Adolescent Psychology*. 
- Mukherjee, S., **Coxe, S.**, Fennie, K., Madhivanan, P., Trepka, M. J. (2017). Stressful life event experiences of pregnant women in the United States: A latent class analysis. *Women’s Health Issues, 27*, 83 – 92. 
- Bagner, D. M., **Coxe, S.**, Hungerford, G. M., Linares, D., Barroso, N., Hernandez, J., Rosa-Olivares, J. (2016). Behavioral parent training in infancy: A window of opportunity for high-risk families. *Journal of Abnormal Child Psychology, 44*, 901-912. doi: 10.1007/s10802-015-0089-5 
