---
title: "Service"
---

***

## Professional Service

- Assistant Director, Data and Methods committee for [Psychological Science Accelerator](https://psysciacc.org/)
- Associate Editor (Methodology) for [Collabra: Psychology](https://online.ucpress.edu/collabra)
- Associate Editor for [Frontiers in Psychology: Quantitative Psychology and Measurement](https://www.frontiersin.org/journals/psychology/sections/quantitative-psychology-and-measurement#)
- Ad Hoc Reviewer for 13 journals and 3 book publishers
- Statistical reviewer for Congressionally Directed Medical Research Program (CDMRP) grant applications
- Professional affiliations:
    - [Society for Prevention Research](https://www.preventionresearch.org/)
    - [American Psychological Association (Division 5)](https://www.apadivisions.org/division-5/index)
    - [American Statistical Association](https://www.amstat.org/)

## University service

- Florida International University
    - Chair or co-chair on 3 dissertation committees
    - Committee member on 30+ dissertation committees in Psychology, Epidemiology, Social Work, Biostatistics 
    - Committee member on 10 thesis committees  

## Department service

- Florida International University
    - Statistical consulting for faculty and graduate students
    - Colloquium Committee (member and chair)
    - Bylaws Revision Committee (member and chair)  
    - Personnel Practices Committee (member)  


 
